apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lychee-data
  namespace: lychee
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
