apiVersion: apps/v1
kind: Deployment
metadata:
  name: lychee
  namespace: lychee
  labels:
    app: lychee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lychee
  template:
    metadata:
      labels:
        app: lychee
    spec:
      initContainers:
      - name: wait-for-postgres
        image: busybox:1.36
        command: ['sh', '-c', 'until nc -z postgres 5432; do echo waiting for postgres; sleep 2; done;']
      containers:
      - name: lychee
        image: lycheeorg/lychee:latest
        ports:
        - containerPort: 80
          name: http
        envFrom:
        - configMapRef:
            name: lychee-config
        - secretRef:
            name: lychee-secrets
        volumeMounts:
        - name: lychee-data
          mountPath: /conf
        - name: lychee-data
          mountPath: /uploads
          subPath: uploads
        - name: lychee-data
          mountPath: /sym
          subPath: sym
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: lychee-data
        persistentVolumeClaim:
          claimName: lychee-data
